#!/bin/bash

# Script to wait for a specific host and port to become available before executing a command.

set -e

host="$1"
port="$2"
shift 2
cmd="$@"

until nc -z -w 1 "$host" "$port"; do
  >&2 echo "Host at $host:$port is unavailable - sleeping"
  sleep 1
done

>&2 echo "Host at $host:$port is up - executing command"
exec sh -c "$cmd"
